### ISSUE TITLE
Forking opencollective-frontend

### ISSUE THREAD

**Issue by mhulet** [opencollective/community#15]
@xdamman @danielsum Would we fork opencollective-frontend here?

- If yes, how can we fork it in this specific repository, not in a new one?
- If no, then we probably want to fork it into a new opencollective/community-frontend repository

At the early beginning, we created another org on GitHub, that we might delete afterwards:
https://github.com/opencollective-community

Let me know about your thoughts and let's move on, we need code to work on :)

**Comment by xdamman** [comment]
I don’t have a strong opinion. Intuitively I’d say that we should use this repo to keep things simple. I also like the idea of a mono repo that links to other things as needed.

**Comment by danielsum** [comment]
I think we should create different repo.

And create a mono repo (at least to centralize issues)

--
Daniel Sum

**Comment by mhulet** [comment]
We will probably end up having multiple repositories, so let's fork `opencollective-frontend` as `community-frontend`, and keep this `community` repository for getting organised (issues, projects, wiki).

But GitHub doesn't allow forking a project to the same organization (that's what we want to do). See https://github.community/t5/Support-Protips/Alternatives-to-forking-into-the-same-account/ba-p/7428.

What they suggest is to duplicate the repository and adding a remote, allowing pulls but not shared pull requests. Maybe this is the best option for now. @xdamman Could you have a look and duplicate `opencollective/opencollective-frontend` to a new `opencollective/community-frontend` repository?

In case this brings back the idea of having our own organization on GitHub, shoot here and let us know.
